doc-valid-idents = []

allowed-duplicate-crates = [
    "base64",
    "darling",
    "darling_core",
    "darling_macro",
    "fastrand",
    "futures-lite",
    "getrandom",
    "infer",
    "rand",
    "rand_chacha",
    "rand_core",
    "serde_qs",
    "syn",
    "thiserror",
    "thiserror-impl",
]
